### ISSUE TITLE
How are camera translations scaled?

### ISSUE THREAD

**Issue by NagabhushanSN95** [barbararoessle/dense_depth_priors_nerf#5]
Hi,

I've a dataset of images with given camera intrinsics and extrinsics (pose). So, I'm trying to generate the `transforms_train.json` file without needing to run colmap and other stuff. To do this, I'm trying to figure out how `transforms_train.json` is created based on colmap sparse reconstruction for the ScanNet scenes. I figured out the relation between rotation matrices, however, I'm not able to figure out how translation is scaled. I found different scaling factors for the 5 scenes. I tried to understand the C++ code that generates the `transforms_train.json` file, but I'm not used to C++ and hence couldn't figure it out.

Can you please tell me how to compute the scaling factor for the camera translation?

PS: I also noticed that, unlike the original NeRF which scales translation so that nearest depth becomes unity, you do not do such a scaling here.

**Comment by barbararoessle** [comment]
[Here](https://github.com/barbararoessle/dense_depth_priors_nerf/issues/1#issuecomment-1111434503) is an explanation on the content of `transforms_train.json` and the definition of the transformation matrix. Does this answer your question?

In the preprocessing on the ScanNet SfM reconstructions we apply a scaling to the reconstruction (sparse depth and poses), because SfM reconstructions are only upto a scaling factor. This scaling allows to compute depth metrics against the ScanNet sensor depth. 
Scaling of the sparse depth and poses is needed only when:
- you have ground truth depth to evaluate against with different scaling than the camera poses and sparse depth, or
- the depth prior network was trained on a different range of sparse depth.

**Comment by NagabhushanSN95** [comment]
Thanks, Barbara! This helps :)
